# Generated by Django 5.2 on 2026-07-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonTeams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon/'),
        ),
        migrations.AlterField(
            model_name='teampokemon',
            name='ability',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='teampokemon',
            name='item',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='teampokemon',
            name='move1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='teampokemon',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teampokemon',
            name='nature',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
